### ISSUE TITLE
Error getting started

### ISSUE THREAD

**Issue by uqcgreen** [iansawyerva/generator-angular-material#1]
I thought I'd give this a go on Mac OSX, and this is as far as I got.

sudo npm install -g yo
sudo npm install -g generator-angular-material
yo angular-material pro-ject
cd pro-ject
gulp serve

[22:24:03] Using gulpfile ~/path/to/project/gulpfile.js
[22:24:03] Starting 'sass'...
[22:24:03] Starting 'index'...
[22:24:03] Starting 'index:dist'...
[22:24:03] Starting 'js'...
[22:24:03] Starting 'uglify-js'...
[22:24:03] Starting 'image'...
[22:24:03] Starting 'image-min'...
[22:24:03] Finished 'image-min' after 2.47 ms
[22:24:03] Starting 'html'...
[22:24:03] gulp-imagemin: Minified 0 images
[22:24:03] gulp-inject 8 files into index.html.
[22:24:03] gulp-inject 11 files into index.html.
[22:24:03] Finished 'index:dist' after 99 ms
[22:24:03] Finished 'image' after 119 ms
[22:24:03] Finished 'index' after 133 ms
[22:24:03] Starting 'bower'...

stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
GulpUglifyError: unable to minify JavaScript
    at createError (/path/to/project/node_modules/gulp-uglify/lib/create-error.js:6:14)
  at wrapper (/path/to/project/node_modules/gulp-uglify/node_modules/lodash/_createHybrid.js:87:15)
    at trycatch (/path/to/project/node_modules/gulp-uglify/minifier.js:26:12)
    at DestroyableTransform.minify [as _transform] (/path/to/project/node_modules/gulp-uglify/minifier.js:76:19)
    at DestroyableTransform.Transform._read (/path/to/project/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/path/to/project/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/path/to/project/node_modules/readable-stream/lib/_stream_writable.js:347:64)
    at writeOrBuffer (/path/to/project/node_modules/readable-stream/lib/_stream_writable.js:336:5)
    at DestroyableTransform.Writable.write (/path/to/project/node_modules/readable-stream/lib/_stream_writable.js:274:11)
    at DestroyableTransform.ondata (stream.js:31:26)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:188:7)
    at DestroyableTransform.<anonymous> (/path/to/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:786:14)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:185:7)
    at emitReadable_ (/path/to/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:448:10)

Is there anyway you could either warn if there are unacceptable characters in the project name, or automatically camel case it?

**Comment by iansawyerva** [comment]
^Noted and will fix.

**Comment by masalinas** [comment]
This error continues with any resolution. Do you know how resolve it?. Is imposible start any project with for example this character '-'

Regards
